version: '3'
services:
  app:
    container_name: backend
    build: ./server/.
    ports:
      - 5000
    links:
      - mongo
    depends_on:
      - mongo
  
  
  mongo:
    container_name: database
    image: mongo
    ports:
      - 27017
